<?php
define('_DB_SERVER_', '');
define('_DB_NAME_', '');
define('_DB_USER_', '');
define('_DB_PASSWD_', '');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheFs');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', '');
define('_COOKIE_IV_', '');
define('_PS_CREATION_DATE_', '2015-09-16');
if (!defined('_PS_VERSION_'))
    define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', '');
define('_RIJNDAEL_IV_', '==');