<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'citymoto_db');
define('_DB_USER_', 'root');
define('_DB_PASSWD_', '');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '1');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'z5RPbOSbgW5iqeMUnuYcXvX0ZoZ56fSojIN6JNZv4Cp77nmQSVp4x9tH');
define('_COOKIE_IV_', 'PCzeZCR0');
define('_PS_CREATION_DATE_', '2015-09-16');
if (!defined('_PS_VERSION_'))
    define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', 'A4j6YfF4fGDtaYETdofWuQAZF3Z8ZBJn');
define('_RIJNDAEL_IV_', 'cEAbHzSpu0WMjpaaIzcTKA==');